package simpledb;
import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends AbstractDbIterator {
    private final JoinPredicate pred;
    private final DbIterator child1;
    private final DbIterator child2;
    private Tuple curTuple1;
    private final TupleDesc tupleDesc;

    /**
     * Constructor.  Accepts to children to join and the predicate
     * to join them on
     *
     * @param p The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.pred = p;
        this.child1 = child1;
        this.child2 = child2;
        this.curTuple1 = null;
        this.tupleDesc = TupleDesc.combine(child1.getTupleDesc(), child2.getTupleDesc());
    }

    /**
     * @see simpledb.TupleDesc#combine(TupleDesc, TupleDesc) for possible implementation logic.
     */
    @Override
    public TupleDesc getTupleDesc() {
        return tupleDesc;
    }

    @Override
    public void open()
        throws DbException, NoSuchElementException, TransactionAbortedException {
        child1.open();
        child2.open();
    }

    @Override
    public void close() {
        super.close();
        child1.close();
        child2.close();
        curTuple1 = null;
    }

    @Override
    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no more tuples.
     * Logically, this is the next tuple in r1 cross r2 that satisfies the join
     * predicate.  There are many possible implementations; the simplest is a
     * nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of
     * Join are simply the concatenation of joining tuples from the left and
     * right relation. Therefore, if an equality predicate is used 
     * there will be two copies of the join attribute
     * in the results.  (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple readNext() throws TransactionAbortedException, DbException {
        if (curTuple1 == null && child1.hasNext()) {
            curTuple1 = child1.next();
        }
        if (curTuple1 != null) {
            while (true) {
                Tuple t1 = curTuple1;
                while (child2.hasNext()) {
                    Tuple t2 = child2.next();
                    if (pred.filter(t1, t2)) {
                        final int t1Len = t1.getTupleDesc().numFields();
                        final int t2Len = t2.getTupleDesc().numFields();
                        Tuple result = new Tuple(getTupleDesc());
                        for (int i = 0; i < t1Len; ++i) {
                            result.setField(i, t1.getField(i));
                        }
                        for (int i = 0; i < t2Len; ++i) {
                            result.setField(i + t1Len, t2.getField(i));
                        }
                        return result;
                    }
                }
                if (child1.hasNext()) {
                    child2.rewind();
                    curTuple1 = child1.next();
                } else {
                    curTuple1 = null;
                    break;
                }
            }
        }
        return null;
    }
}
